-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 22:49:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sed
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sed` DEFAULT CHARACTER SET utf8 ;
USE `db_sed` ;

-- -----------------------------------------------------
-- Table `db_sed`.`Colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Colaboradores` (
  `id_Colaborador` INT NOT NULL AUTO_INCREMENT,
  `id_Jefe` INT NULL,
  `dni` VARCHAR(10) NULL,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  `fechaNac` DATE NULL,
  `contraseña` VARCHAR(150) NULL,
  `estadoCuenta` TINYINT(5) NULL,
  `esAdmin` TINYINT(1) NULL,
  PRIMARY KEY (`id_Colaborador`),
  INDEX `fk_Colaboradores_Colaboradores1_idx` (`id_Jefe` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_Colaboradores_Colaboradores1`
    FOREIGN KEY (`id_Jefe`)
    REFERENCES `db_sed`.`Colaboradores` (`id_Colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Periodos` (
  `id_Periodo` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `pesoEvalObj` DOUBLE NULL,
  `pesoEvalComp` DOUBLE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Escalas` (
  `id_Escala` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo` TINYINT(1) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Escala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Evaluaciones` (
  `id_Evaluacion` INT NOT NULL AUTO_INCREMENT,
  `id_Colaborador` INT NOT NULL,
  `id_Periodo` INT NOT NULL,
  `id_EscalaPreCupos` INT NULL,
  `id_EscalaSinCalibrar` INT NULL,
  `id_EscalaFinal` INT NULL,
  `estadoPDI` INT NULL,
  `observaciones` VARCHAR(200) NULL,
  `notaAutoEval` DOUBLE NULL,
  `notaFinal` DOUBLE NULL,
  `tipo` TINYINT(1) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Evaluacion`),
  INDEX `fk_Evaluaciones_Colaboradores1_idx` (`id_Colaborador` ASC) VISIBLE,
  INDEX `fk_Evaluaciones_Periodos1_idx` (`id_Periodo` ASC) VISIBLE,
  INDEX `fk_Evaluaciones_Escalas1_idx` (`id_EscalaSinCalibrar` ASC) VISIBLE,
  INDEX `fk_Evaluaciones_Escalas2_idx` (`id_EscalaFinal` ASC) VISIBLE,
  INDEX `fk_Evaluaciones_Escalas3_idx` (`id_EscalaPreCupos` ASC) VISIBLE,
  CONSTRAINT `fk_Evaluaciones_Colaboradores1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `db_sed`.`Colaboradores` (`id_Colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluaciones_Periodos1`
    FOREIGN KEY (`id_Periodo`)
    REFERENCES `db_sed`.`Periodos` (`id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluaciones_Escalas1`
    FOREIGN KEY (`id_EscalaSinCalibrar`)
    REFERENCES `db_sed`.`Escalas` (`id_Escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluaciones_Escalas2`
    FOREIGN KEY (`id_EscalaFinal`)
    REFERENCES `db_sed`.`Escalas` (`id_Escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluaciones_Escalas3`
    FOREIGN KEY (`id_EscalaPreCupos`)
    REFERENCES `db_sed`.`Escalas` (`id_Escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`EvaluacionesDesempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`EvaluacionesDesempenho` (
  `id_Evaluacion` INT NOT NULL,
  `observacionesComp` VARCHAR(100) NULL,
  `notaAutoEvalComp` DOUBLE NULL,
  `notaPreviaComp` DOUBLE NULL,
  `notaFinalComp` DOUBLE NULL,
  `observacionesObj` VARCHAR(100) NULL,
  `notaAutoEvalObj` DOUBLE NULL,
  `notaPreviaObj` DOUBLE NULL,
  `notaFinalObj` DOUBLE NULL,
  `notaPrevia` DOUBLE NULL,
  PRIMARY KEY (`id_Evaluacion`),
  CONSTRAINT `fk_EvaluacionesDesempenho_Evaluaciones1`
    FOREIGN KEY (`id_Evaluacion`)
    REFERENCES `db_sed`.`Evaluaciones` (`id_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Objetivos` (
  `id_Objetivo` INT NOT NULL AUTO_INCREMENT,
  `id_Colaborador` INT NULL,
  `id_Evaluacion` INT NULL,
  `descripcion` VARCHAR(200) NULL,
  `estado` INT NULL,
  `fechaFormulacion` DATE NULL,
  `fechaAprobacion` DATE NULL,
  `meta` DOUBLE NULL,
  `unidadMedida` VARCHAR(50) NULL,
  `observacion` VARCHAR(200) NULL,
  `peso` DOUBLE NULL,
  `notaPrevia` DOUBLE NULL,
  `notaAutoEval` DOUBLE NULL,
  `notaFinal` DOUBLE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Objetivo`),
  INDEX `fk_Objetivos_Colaboradores_idx` (`id_Colaborador` ASC) VISIBLE,
  INDEX `fk_Objetivos_EvaluacionesDesempenho1_idx` (`id_Evaluacion` ASC) VISIBLE,
  CONSTRAINT `fk_Objetivos_Colaboradores`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `db_sed`.`Colaboradores` (`id_Colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objetivos_EvaluacionesDesempenho1`
    FOREIGN KEY (`id_Evaluacion`)
    REFERENCES `db_sed`.`EvaluacionesDesempenho` (`id_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`PuestosTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`PuestosTrabajo` (
  `id_PuestosTrabajo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(150) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_PuestosTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Criterios` (
  `id_Criterio` INT NOT NULL AUTO_INCREMENT,
  `id_CriterioPadre` INT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(150) NULL,
  `esVigente` TINYINT(1) NULL,
  `tipo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Criterio`),
  INDEX `fk_Criterios_Criterios1_idx` (`id_CriterioPadre` ASC) VISIBLE,
  CONSTRAINT `fk_Criterios_Criterios1`
    FOREIGN KEY (`id_CriterioPadre`)
    REFERENCES `db_sed`.`Criterios` (`id_Criterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`ItemsPDI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`ItemsPDI` (
  `id_ItemPDI` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_ItemPDI`))
ENGINE = InnoDB
COMMENT = 'I';


-- -----------------------------------------------------
-- Table `db_sed`.`Escalas_Periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Escalas_Periodos` (
  `id_Escala` INT NOT NULL,
  `id_Periodo` INT NOT NULL,
  `notaMax` DOUBLE NULL,
  `notaMin` DOUBLE NULL,
  `porcentajeCupos` DOUBLE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Escala`, `id_Periodo`),
  INDEX `fk_Escalas_has_Periodos_Periodos1_idx` (`id_Periodo` ASC) VISIBLE,
  INDEX `fk_Escalas_has_Periodos_Escalas1_idx` (`id_Escala` ASC) VISIBLE,
  CONSTRAINT `fk_Escalas_has_Periodos_Escalas1`
    FOREIGN KEY (`id_Escala`)
    REFERENCES `db_sed`.`Escalas` (`id_Escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escalas_has_Periodos_Periodos1`
    FOREIGN KEY (`id_Periodo`)
    REFERENCES `db_sed`.`Periodos` (`id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`ItemsPDI_Periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`ItemsPDI_Periodos` (
  `id_ItemPDI` INT NOT NULL,
  `id_Periodo` INT NOT NULL,
  `notaMin` DOUBLE NULL,
  `notaMax` DOUBLE NULL,
  PRIMARY KEY (`id_ItemPDI`, `id_Periodo`),
  INDEX `fk_ItemsPDI_has_Periodos_Periodos1_idx` (`id_Periodo` ASC) VISIBLE,
  INDEX `fk_ItemsPDI_has_Periodos_ItemsPDI1_idx` (`id_ItemPDI` ASC) VISIBLE,
  CONSTRAINT `fk_ItemsPDI_has_Periodos_ItemsPDI1`
    FOREIGN KEY (`id_ItemPDI`)
    REFERENCES `db_sed`.`ItemsPDI` (`id_ItemPDI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemsPDI_has_Periodos_Periodos1`
    FOREIGN KEY (`id_Periodo`)
    REFERENCES `db_sed`.`Periodos` (`id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`PesosCriterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`PesosCriterios` (
  `id_PesoCriterio` INT NOT NULL AUTO_INCREMENT,
  `id_Periodo` INT NOT NULL,
  `id_Criterio` INT NOT NULL,
  `id_PuestosTrabajo` INT NOT NULL,
  `peso` DOUBLE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_PesoCriterio`),
  INDEX `fk_Areas_PuestosTrabajo_has_Periodos_Periodos1_idx` (`id_Periodo` ASC) VISIBLE,
  INDEX `fk_Areas_PuestosTrabajo_has_Periodos_Criterios1_idx` (`id_Criterio` ASC) VISIBLE,
  INDEX `fk_PesosCriterios_PuestosTrabajo1_idx` (`id_PuestosTrabajo` ASC) VISIBLE,
  CONSTRAINT `fk_Areas_PuestosTrabajo_has_Periodos_Periodos1`
    FOREIGN KEY (`id_Periodo`)
    REFERENCES `db_sed`.`Periodos` (`id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Areas_PuestosTrabajo_has_Periodos_Criterios1`
    FOREIGN KEY (`id_Criterio`)
    REFERENCES `db_sed`.`Criterios` (`id_Criterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PesosCriterios_PuestosTrabajo1`
    FOREIGN KEY (`id_PuestosTrabajo`)
    REFERENCES `db_sed`.`PuestosTrabajo` (`id_PuestosTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Gerencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Gerencias` (
  `id_Gerencias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `descripcion` VARCHAR(200) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Gerencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Gerencia_Periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Gerencia_Periodos` (
  `id_Periodo` INT NOT NULL,
  `id_Gerencias` INT NOT NULL,
  `fechaInicioPlan` DATE NULL,
  `fechaFinPlan` DATE NULL,
  `fechaInicioEval` DATE NULL,
  `fechaFinEval` DATE NULL,
  `fechaInicioPDI` DATE NULL,
  `fechaFinPDI` DATE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Periodo`, `id_Gerencias`),
  INDEX `fk_Periodos_has_Gerencias_Gerencias1_idx` (`id_Gerencias` ASC) VISIBLE,
  INDEX `fk_Periodos_has_Gerencias_Periodos1_idx` (`id_Periodo` ASC) VISIBLE,
  CONSTRAINT `fk_Periodos_has_Gerencias_Periodos1`
    FOREIGN KEY (`id_Periodo`)
    REFERENCES `db_sed`.`Periodos` (`id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Periodos_has_Gerencias_Gerencias1`
    FOREIGN KEY (`id_Gerencias`)
    REFERENCES `db_sed`.`Gerencias` (`id_Gerencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`Colaboradores_GPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`Colaboradores_GPT` (
  `id_Colaborador` INT NOT NULL,
  `id_PuestosTrabajo` INT NOT NULL,
  `id_Periodo` INT NOT NULL,
  `id_Gerencias` INT NOT NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_Colaborador`, `id_PuestosTrabajo`, `id_Periodo`, `id_Gerencias`),
  INDEX `fk_Colaboradores_has_PuestosTrabajo_PuestosTrabajo1_idx` (`id_PuestosTrabajo` ASC) VISIBLE,
  INDEX `fk_Colaboradores_has_PuestosTrabajo_Colaboradores1_idx` (`id_Colaborador` ASC) VISIBLE,
  INDEX `fk_Colaboradores_GPT_Gerencia_Periodos1_idx` (`id_Periodo` ASC, `id_Gerencias` ASC) VISIBLE,
  CONSTRAINT `fk_Colaboradores_has_PuestosTrabajo_Colaboradores1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `db_sed`.`Colaboradores` (`id_Colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaboradores_has_PuestosTrabajo_PuestosTrabajo1`
    FOREIGN KEY (`id_PuestosTrabajo`)
    REFERENCES `db_sed`.`PuestosTrabajo` (`id_PuestosTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaboradores_GPT_Gerencia_Periodos1`
    FOREIGN KEY (`id_Periodo` , `id_Gerencias`)
    REFERENCES `db_sed`.`Gerencia_Periodos` (`id_Periodo` , `id_Gerencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sed`.`LineasEvaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sed`.`LineasEvaluacion` (
  `id_LineasEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `id_Evaluacion` INT NOT NULL,
  `id_ItemPDI` INT NOT NULL,
  `id_LineasEvaluacionPadre` INT NOT NULL,
  `id_PesoCriterio` INT NOT NULL,
  `notaAutoEval` DOUBLE NULL,
  `notaPrevia` DOUBLE NULL,
  `notaFinal` DOUBLE NULL,
  `acccionesAtomar` VARCHAR(500) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_LineasEvaluacion`),
  INDEX `fk_LineasEvaluacion_Evaluaciones1_idx` (`id_Evaluacion` ASC) VISIBLE,
  INDEX `fk_LineasEvaluacion_ItemsPDI1_idx` (`id_ItemPDI` ASC) VISIBLE,
  INDEX `fk_LineasEvaluacion_LineasEvaluacion1_idx` (`id_LineasEvaluacionPadre` ASC) VISIBLE,
  INDEX `fk_LineasEvaluacion_PesosCriterios1_idx` (`id_PesoCriterio` ASC) VISIBLE,
  CONSTRAINT `fk_LineasEvaluacion_Evaluaciones1`
    FOREIGN KEY (`id_Evaluacion`)
    REFERENCES `db_sed`.`Evaluaciones` (`id_Evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineasEvaluacion_ItemsPDI1`
    FOREIGN KEY (`id_ItemPDI`)
    REFERENCES `db_sed`.`ItemsPDI` (`id_ItemPDI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineasEvaluacion_LineasEvaluacion1`
    FOREIGN KEY (`id_LineasEvaluacionPadre`)
    REFERENCES `db_sed`.`LineasEvaluacion` (`id_LineasEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineasEvaluacion_PesosCriterios1`
    FOREIGN KEY (`id_PesoCriterio`)
    REFERENCES `db_sed`.`PesosCriterios` (`id_PesoCriterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
