//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEDInterfaces.ObjetivoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sed.pucp.edu.pe/", ConfigurationName="ObjetivoWS.ObjetivoWS")]
    public interface ObjetivoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/actualizarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/actualizarObjetivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(evaluacion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse actualizarObjetivo(SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/actualizarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/actualizarObjetivoResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse> actualizarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/insertarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/insertarObjetivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(evaluacion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse insertarObjetivo(SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/insertarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/insertarObjetivoResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse> insertarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/eliminarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/eliminarObjetivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(evaluacion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse eliminarObjetivo(SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/eliminarObjetivoRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/eliminarObjetivoResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse> eliminarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(evaluacion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse listarObjetivos(SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse> listarObjetivosAsync(SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosXColaboradorRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosXColaboradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(evaluacion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse listarObjetivosXColaborador(SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosXColaboradorRequest", ReplyAction="http://services.sed.pucp.edu.pe/ObjetivoWS/listarObjetivosXColaboradorResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse> listarObjetivosXColaboradorAsync(SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class objetivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private colaborador colaboradorField;
        
        private string descripcionField;
        
        private bool estadoField;
        
        private evaluacionDesempenho evaluacionField;
        
        private System.DateTime fechaAprobacionField;
        
        private bool fechaAprobacionFieldSpecified;
        
        private System.DateTime fechaFormulacionField;
        
        private bool fechaFormulacionFieldSpecified;
        
        private int idObjetivoField;
        
        private double metaField;
        
        private double notaAutoEvalField;
        
        private double notaFinalField;
        
        private double notaPreviaField;
        
        private string observacionField;
        
        private periodo periodoField;
        
        private double pesoField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public colaborador colaborador {
            get {
                return this.colaboradorField;
            }
            set {
                this.colaboradorField = value;
                this.RaisePropertyChanged("colaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public evaluacionDesempenho evaluacion {
            get {
                return this.evaluacionField;
            }
            set {
                this.evaluacionField = value;
                this.RaisePropertyChanged("evaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaAprobacion {
            get {
                return this.fechaAprobacionField;
            }
            set {
                this.fechaAprobacionField = value;
                this.RaisePropertyChanged("fechaAprobacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAprobacionSpecified {
            get {
                return this.fechaAprobacionFieldSpecified;
            }
            set {
                this.fechaAprobacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaAprobacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaFormulacion {
            get {
                return this.fechaFormulacionField;
            }
            set {
                this.fechaFormulacionField = value;
                this.RaisePropertyChanged("fechaFormulacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFormulacionSpecified {
            get {
                return this.fechaFormulacionFieldSpecified;
            }
            set {
                this.fechaFormulacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaFormulacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idObjetivo {
            get {
                return this.idObjetivoField;
            }
            set {
                this.idObjetivoField = value;
                this.RaisePropertyChanged("idObjetivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
                this.RaisePropertyChanged("meta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double notaAutoEval {
            get {
                return this.notaAutoEvalField;
            }
            set {
                this.notaAutoEvalField = value;
                this.RaisePropertyChanged("notaAutoEval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double notaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
                this.RaisePropertyChanged("notaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double notaPrevia {
            get {
                return this.notaPreviaField;
            }
            set {
                this.notaPreviaField = value;
                this.RaisePropertyChanged("notaPrevia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("peso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class colaborador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacField;
        
        private bool fechaNacFieldSpecified;
        
        private gerencia gerenciaField;
        
        private int idColaboradorField;
        
        private colaborador jefeField;
        
        private string nombresField;
        
        private periodo periodoField;
        
        private puestoTrabajo puestoTrabajoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
                this.RaisePropertyChanged("fechaNac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacSpecified {
            get {
                return this.fechaNacFieldSpecified;
            }
            set {
                this.fechaNacFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public gerencia gerencia {
            get {
                return this.gerenciaField;
            }
            set {
                this.gerenciaField = value;
                this.RaisePropertyChanged("gerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idColaborador {
            get {
                return this.idColaboradorField;
            }
            set {
                this.idColaboradorField = value;
                this.RaisePropertyChanged("idColaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public colaborador jefe {
            get {
                return this.jefeField;
            }
            set {
                this.jefeField = value;
                this.RaisePropertyChanged("jefe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public puestoTrabajo puestoTrabajo {
            get {
                return this.puestoTrabajoField;
            }
            set {
                this.puestoTrabajoField = value;
                this.RaisePropertyChanged("puestoTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class gerencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idGerenciaField;
        
        private string nombreField;
        
        private periodo periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idGerencia {
            get {
                return this.idGerenciaField;
            }
            set {
                this.idGerenciaField = value;
                this.RaisePropertyChanged("idGerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class periodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime diaNotificacionField;
        
        private bool diaNotificacionFieldSpecified;
        
        private estadoPeriodo estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private time horaNotificacionField;
        
        private int idPeriodoField;
        
        private string nombreField;
        
        private double pesoEvalCompField;
        
        private double pesoEvalObjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime diaNotificacion {
            get {
                return this.diaNotificacionField;
            }
            set {
                this.diaNotificacionField = value;
                this.RaisePropertyChanged("diaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaNotificacionSpecified {
            get {
                return this.diaNotificacionFieldSpecified;
            }
            set {
                this.diaNotificacionFieldSpecified = value;
                this.RaisePropertyChanged("diaNotificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPeriodo estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public time horaNotificacion {
            get {
                return this.horaNotificacionField;
            }
            set {
                this.horaNotificacionField = value;
                this.RaisePropertyChanged("horaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPeriodo {
            get {
                return this.idPeriodoField;
            }
            set {
                this.idPeriodoField = value;
                this.RaisePropertyChanged("idPeriodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pesoEvalComp {
            get {
                return this.pesoEvalCompField;
            }
            set {
                this.pesoEvalCompField = value;
                this.RaisePropertyChanged("pesoEvalComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double pesoEvalObj {
            get {
                return this.pesoEvalObjField;
            }
            set {
                this.pesoEvalObjField = value;
                this.RaisePropertyChanged("pesoEvalObj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public enum estadoPeriodo {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        ELIMINADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class time : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class escala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEscalaField;
        
        private string nombreField;
        
        private bool tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEscala {
            get {
                return this.idEscalaField;
            }
            set {
                this.idEscalaField = value;
                this.RaisePropertyChanged("idEscala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(evaluacionDesempenho))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class evaluacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private colaborador colaboradorField;
        
        private escala escalaFinalField;
        
        private escala escalaPreCuposField;
        
        private escala escalaSinCalibrarField;
        
        private estadoEvaluacion estadoField;
        
        private bool estadoFieldSpecified;
        
        private int estadoPDIField;
        
        private int idEvaluacionField;
        
        private double notaAutoEvalField;
        
        private double notaFinalField;
        
        private string observacionesField;
        
        private periodo periodoField;
        
        private bool tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public colaborador colaborador {
            get {
                return this.colaboradorField;
            }
            set {
                this.colaboradorField = value;
                this.RaisePropertyChanged("colaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public escala escalaFinal {
            get {
                return this.escalaFinalField;
            }
            set {
                this.escalaFinalField = value;
                this.RaisePropertyChanged("escalaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public escala escalaPreCupos {
            get {
                return this.escalaPreCuposField;
            }
            set {
                this.escalaPreCuposField = value;
                this.RaisePropertyChanged("escalaPreCupos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public escala escalaSinCalibrar {
            get {
                return this.escalaSinCalibrarField;
            }
            set {
                this.escalaSinCalibrarField = value;
                this.RaisePropertyChanged("escalaSinCalibrar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoEvaluacion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int estadoPDI {
            get {
                return this.estadoPDIField;
            }
            set {
                this.estadoPDIField = value;
                this.RaisePropertyChanged("estadoPDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idEvaluacion {
            get {
                return this.idEvaluacionField;
            }
            set {
                this.idEvaluacionField = value;
                this.RaisePropertyChanged("idEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double notaAutoEval {
            get {
                return this.notaAutoEvalField;
            }
            set {
                this.notaAutoEvalField = value;
                this.RaisePropertyChanged("notaAutoEval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double notaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
                this.RaisePropertyChanged("notaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public enum estadoEvaluacion {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        ELIMINADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class evaluacionDesempenho : evaluacion {
        
        private double notaAutoEvalCompField;
        
        private double notaAutoEvalObjField;
        
        private double notaFinalCompField;
        
        private double notaFinalObjField;
        
        private double notaPreviaField;
        
        private double notaPreviaCompField;
        
        private double notaPreviaObjField;
        
        private string observacionesCompField;
        
        private string observacionesObjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double notaAutoEvalComp {
            get {
                return this.notaAutoEvalCompField;
            }
            set {
                this.notaAutoEvalCompField = value;
                this.RaisePropertyChanged("notaAutoEvalComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double notaAutoEvalObj {
            get {
                return this.notaAutoEvalObjField;
            }
            set {
                this.notaAutoEvalObjField = value;
                this.RaisePropertyChanged("notaAutoEvalObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double notaFinalComp {
            get {
                return this.notaFinalCompField;
            }
            set {
                this.notaFinalCompField = value;
                this.RaisePropertyChanged("notaFinalComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double notaFinalObj {
            get {
                return this.notaFinalObjField;
            }
            set {
                this.notaFinalObjField = value;
                this.RaisePropertyChanged("notaFinalObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double notaPrevia {
            get {
                return this.notaPreviaField;
            }
            set {
                this.notaPreviaField = value;
                this.RaisePropertyChanged("notaPrevia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double notaPreviaComp {
            get {
                return this.notaPreviaCompField;
            }
            set {
                this.notaPreviaCompField = value;
                this.RaisePropertyChanged("notaPreviaComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double notaPreviaObj {
            get {
                return this.notaPreviaObjField;
            }
            set {
                this.notaPreviaObjField = value;
                this.RaisePropertyChanged("notaPreviaObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string observacionesComp {
            get {
                return this.observacionesCompField;
            }
            set {
                this.observacionesCompField = value;
                this.RaisePropertyChanged("observacionesComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string observacionesObj {
            get {
                return this.observacionesObjField;
            }
            set {
                this.observacionesObjField = value;
                this.RaisePropertyChanged("observacionesObj");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class puestoTrabajo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private gerencia gerenciaField;
        
        private int idPuestoTrabajoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public gerencia gerencia {
            get {
                return this.gerenciaField;
            }
            set {
                this.gerenciaField = value;
                this.RaisePropertyChanged("gerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPuestoTrabajo {
            get {
                return this.idPuestoTrabajoField;
            }
            set {
                this.idPuestoTrabajoField = value;
                this.RaisePropertyChanged("idPuestoTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarObjetivo", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarObjetivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ObjetivoWS.objetivo objetivo;
        
        public actualizarObjetivoRequest() {
        }
        
        public actualizarObjetivoRequest(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            this.objetivo = objetivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarObjetivoResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarObjetivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarObjetivoResponse() {
        }
        
        public actualizarObjetivoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarObjetivo", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarObjetivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ObjetivoWS.objetivo objetivo;
        
        public insertarObjetivoRequest() {
        }
        
        public insertarObjetivoRequest(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            this.objetivo = objetivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarObjetivoResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarObjetivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarObjetivoResponse() {
        }
        
        public insertarObjetivoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarObjetivo", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarObjetivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idObjetivo;
        
        public eliminarObjetivoRequest() {
        }
        
        public eliminarObjetivoRequest(int idObjetivo) {
            this.idObjetivo = idObjetivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarObjetivoResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarObjetivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarObjetivoResponse() {
        }
        
        public eliminarObjetivoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarObjetivos", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarObjetivosRequest {
        
        public listarObjetivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarObjetivosResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarObjetivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ObjetivoWS.objetivo[] @return;
        
        public listarObjetivosResponse() {
        }
        
        public listarObjetivosResponse(SistemaEDInterfaces.ObjetivoWS.objetivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarObjetivosXColaborador", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarObjetivosXColaboradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idColaborador;
        
        public listarObjetivosXColaboradorRequest() {
        }
        
        public listarObjetivosXColaboradorRequest(int idColaborador) {
            this.idColaborador = idColaborador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarObjetivosXColaboradorResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarObjetivosXColaboradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ObjetivoWS.objetivo[] @return;
        
        public listarObjetivosXColaboradorResponse() {
        }
        
        public listarObjetivosXColaboradorResponse(SistemaEDInterfaces.ObjetivoWS.objetivo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObjetivoWSChannel : SistemaEDInterfaces.ObjetivoWS.ObjetivoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjetivoWSClient : System.ServiceModel.ClientBase<SistemaEDInterfaces.ObjetivoWS.ObjetivoWS>, SistemaEDInterfaces.ObjetivoWS.ObjetivoWS {
        
        public ObjetivoWSClient() {
        }
        
        public ObjetivoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjetivoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjetivoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjetivoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.actualizarObjetivo(SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest request) {
            return base.Channel.actualizarObjetivo(request);
        }
        
        public int actualizarObjetivo(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest();
            inValue.objetivo = objetivo;
            SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse retVal = ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).actualizarObjetivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse> SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.actualizarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest request) {
            return base.Channel.actualizarObjetivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoResponse> actualizarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.actualizarObjetivoRequest();
            inValue.objetivo = objetivo;
            return ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).actualizarObjetivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.insertarObjetivo(SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest request) {
            return base.Channel.insertarObjetivo(request);
        }
        
        public int insertarObjetivo(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest();
            inValue.objetivo = objetivo;
            SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse retVal = ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).insertarObjetivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse> SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.insertarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest request) {
            return base.Channel.insertarObjetivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.insertarObjetivoResponse> insertarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.objetivo objetivo) {
            SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.insertarObjetivoRequest();
            inValue.objetivo = objetivo;
            return ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).insertarObjetivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.eliminarObjetivo(SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest request) {
            return base.Channel.eliminarObjetivo(request);
        }
        
        public int eliminarObjetivo(int idObjetivo) {
            SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest();
            inValue.idObjetivo = idObjetivo;
            SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse retVal = ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).eliminarObjetivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse> SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.eliminarObjetivoAsync(SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest request) {
            return base.Channel.eliminarObjetivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoResponse> eliminarObjetivoAsync(int idObjetivo) {
            SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest inValue = new SistemaEDInterfaces.ObjetivoWS.eliminarObjetivoRequest();
            inValue.idObjetivo = idObjetivo;
            return ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).eliminarObjetivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.listarObjetivos(SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest request) {
            return base.Channel.listarObjetivos(request);
        }
        
        public SistemaEDInterfaces.ObjetivoWS.objetivo[] listarObjetivos() {
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest inValue = new SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest();
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse retVal = ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).listarObjetivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse> SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.listarObjetivosAsync(SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest request) {
            return base.Channel.listarObjetivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosResponse> listarObjetivosAsync() {
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest inValue = new SistemaEDInterfaces.ObjetivoWS.listarObjetivosRequest();
            return ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).listarObjetivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.listarObjetivosXColaborador(SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest request) {
            return base.Channel.listarObjetivosXColaborador(request);
        }
        
        public SistemaEDInterfaces.ObjetivoWS.objetivo[] listarObjetivosXColaborador(int idColaborador) {
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest inValue = new SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest();
            inValue.idColaborador = idColaborador;
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse retVal = ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).listarObjetivosXColaborador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse> SistemaEDInterfaces.ObjetivoWS.ObjetivoWS.listarObjetivosXColaboradorAsync(SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest request) {
            return base.Channel.listarObjetivosXColaboradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorResponse> listarObjetivosXColaboradorAsync(int idColaborador) {
            SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest inValue = new SistemaEDInterfaces.ObjetivoWS.listarObjetivosXColaboradorRequest();
            inValue.idColaborador = idColaborador;
            return ((SistemaEDInterfaces.ObjetivoWS.ObjetivoWS)(this)).listarObjetivosXColaboradorAsync(inValue);
        }
    }
}
