//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEDInterfaces.GerenciaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sed.pucp.edu.pe/", ConfigurationName="GerenciaWS.GerenciaWS")]
    public interface GerenciaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/actualizarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/actualizarGerenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse actualizarGerencia(SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/actualizarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/actualizarGerenciaResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse> actualizarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaPeriodoRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaPeriodoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse insertarGerenciaPeriodo(SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaPeriodoRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaPeriodoResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse> insertarGerenciaPeriodoAsync(SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse insertarGerencia(SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/insertarGerenciaResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse> insertarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/listarGerenciasRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/listarGerenciasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse listarGerencias(SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/listarGerenciasRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/listarGerenciasResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse> listarGerenciasAsync(SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/eliminarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/eliminarGerenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse eliminarGerencia(SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/GerenciaWS/eliminarGerenciaRequest", ReplyAction="http://services.sed.pucp.edu.pe/GerenciaWS/eliminarGerenciaResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse> eliminarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class gerencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idGerenciaField;
        
        private string nombreField;
        
        private periodo periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idGerencia {
            get {
                return this.idGerenciaField;
            }
            set {
                this.idGerenciaField = value;
                this.RaisePropertyChanged("idGerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class periodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime diaNotificacionField;
        
        private bool diaNotificacionFieldSpecified;
        
        private estadoPeriodo estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private time horaNotificacionField;
        
        private int idPeriodoField;
        
        private string nombreField;
        
        private double pesoEvalCompField;
        
        private double pesoEvalObjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime diaNotificacion {
            get {
                return this.diaNotificacionField;
            }
            set {
                this.diaNotificacionField = value;
                this.RaisePropertyChanged("diaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaNotificacionSpecified {
            get {
                return this.diaNotificacionFieldSpecified;
            }
            set {
                this.diaNotificacionFieldSpecified = value;
                this.RaisePropertyChanged("diaNotificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPeriodo estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public time horaNotificacion {
            get {
                return this.horaNotificacionField;
            }
            set {
                this.horaNotificacionField = value;
                this.RaisePropertyChanged("horaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPeriodo {
            get {
                return this.idPeriodoField;
            }
            set {
                this.idPeriodoField = value;
                this.RaisePropertyChanged("idPeriodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pesoEvalComp {
            get {
                return this.pesoEvalCompField;
            }
            set {
                this.pesoEvalCompField = value;
                this.RaisePropertyChanged("pesoEvalComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double pesoEvalObj {
            get {
                return this.pesoEvalObjField;
            }
            set {
                this.pesoEvalObjField = value;
                this.RaisePropertyChanged("pesoEvalObj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public enum estadoPeriodo {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        ELIMINADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class time : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarGerencia", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarGerenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.GerenciaWS.gerencia gerencia;
        
        public actualizarGerenciaRequest() {
        }
        
        public actualizarGerenciaRequest(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            this.gerencia = gerencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarGerenciaResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarGerenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarGerenciaResponse() {
        }
        
        public actualizarGerenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGerenciaPeriodo", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGerenciaPeriodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.GerenciaWS.gerencia gerencia;
        
        public insertarGerenciaPeriodoRequest() {
        }
        
        public insertarGerenciaPeriodoRequest(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            this.gerencia = gerencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGerenciaPeriodoResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGerenciaPeriodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGerenciaPeriodoResponse() {
        }
        
        public insertarGerenciaPeriodoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGerencia", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGerenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.GerenciaWS.gerencia gerencia;
        
        public insertarGerenciaRequest() {
        }
        
        public insertarGerenciaRequest(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            this.gerencia = gerencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGerenciaResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGerenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGerenciaResponse() {
        }
        
        public insertarGerenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGerencias", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGerenciasRequest {
        
        public listarGerenciasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGerenciasResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGerenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.GerenciaWS.gerencia[] @return;
        
        public listarGerenciasResponse() {
        }
        
        public listarGerenciasResponse(SistemaEDInterfaces.GerenciaWS.gerencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGerencia", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarGerenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gerencia;
        
        public eliminarGerenciaRequest() {
        }
        
        public eliminarGerenciaRequest(int gerencia) {
            this.gerencia = gerencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGerenciaResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarGerenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGerenciaResponse() {
        }
        
        public eliminarGerenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GerenciaWSChannel : SistemaEDInterfaces.GerenciaWS.GerenciaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GerenciaWSClient : System.ServiceModel.ClientBase<SistemaEDInterfaces.GerenciaWS.GerenciaWS>, SistemaEDInterfaces.GerenciaWS.GerenciaWS {
        
        public GerenciaWSClient() {
        }
        
        public GerenciaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GerenciaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerenciaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerenciaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse SistemaEDInterfaces.GerenciaWS.GerenciaWS.actualizarGerencia(SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest request) {
            return base.Channel.actualizarGerencia(request);
        }
        
        public int actualizarGerencia(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest();
            inValue.gerencia = gerencia;
            SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse retVal = ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).actualizarGerencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse> SistemaEDInterfaces.GerenciaWS.GerenciaWS.actualizarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest request) {
            return base.Channel.actualizarGerenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.actualizarGerenciaResponse> actualizarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.actualizarGerenciaRequest();
            inValue.gerencia = gerencia;
            return ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).actualizarGerenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse SistemaEDInterfaces.GerenciaWS.GerenciaWS.insertarGerenciaPeriodo(SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest request) {
            return base.Channel.insertarGerenciaPeriodo(request);
        }
        
        public int insertarGerenciaPeriodo(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest inValue = new SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest();
            inValue.gerencia = gerencia;
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse retVal = ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).insertarGerenciaPeriodo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse> SistemaEDInterfaces.GerenciaWS.GerenciaWS.insertarGerenciaPeriodoAsync(SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest request) {
            return base.Channel.insertarGerenciaPeriodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoResponse> insertarGerenciaPeriodoAsync(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest inValue = new SistemaEDInterfaces.GerenciaWS.insertarGerenciaPeriodoRequest();
            inValue.gerencia = gerencia;
            return ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).insertarGerenciaPeriodoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse SistemaEDInterfaces.GerenciaWS.GerenciaWS.insertarGerencia(SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest request) {
            return base.Channel.insertarGerencia(request);
        }
        
        public int insertarGerencia(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest();
            inValue.gerencia = gerencia;
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse retVal = ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).insertarGerencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse> SistemaEDInterfaces.GerenciaWS.GerenciaWS.insertarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest request) {
            return base.Channel.insertarGerenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.insertarGerenciaResponse> insertarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.gerencia gerencia) {
            SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.insertarGerenciaRequest();
            inValue.gerencia = gerencia;
            return ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).insertarGerenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse SistemaEDInterfaces.GerenciaWS.GerenciaWS.listarGerencias(SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest request) {
            return base.Channel.listarGerencias(request);
        }
        
        public SistemaEDInterfaces.GerenciaWS.gerencia[] listarGerencias() {
            SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest inValue = new SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest();
            SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse retVal = ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).listarGerencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse> SistemaEDInterfaces.GerenciaWS.GerenciaWS.listarGerenciasAsync(SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest request) {
            return base.Channel.listarGerenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.listarGerenciasResponse> listarGerenciasAsync() {
            SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest inValue = new SistemaEDInterfaces.GerenciaWS.listarGerenciasRequest();
            return ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).listarGerenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse SistemaEDInterfaces.GerenciaWS.GerenciaWS.eliminarGerencia(SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest request) {
            return base.Channel.eliminarGerencia(request);
        }
        
        public int eliminarGerencia(int gerencia) {
            SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest();
            inValue.gerencia = gerencia;
            SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse retVal = ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).eliminarGerencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse> SistemaEDInterfaces.GerenciaWS.GerenciaWS.eliminarGerenciaAsync(SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest request) {
            return base.Channel.eliminarGerenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.GerenciaWS.eliminarGerenciaResponse> eliminarGerenciaAsync(int gerencia) {
            SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest inValue = new SistemaEDInterfaces.GerenciaWS.eliminarGerenciaRequest();
            inValue.gerencia = gerencia;
            return ((SistemaEDInterfaces.GerenciaWS.GerenciaWS)(this)).eliminarGerenciaAsync(inValue);
        }
    }
}
