//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEDInterfaces.ColaboradorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sed.pucp.edu.pe/", ConfigurationName="ColaboradorWS.ColaboradorWS")]
    public interface ColaboradorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/insertarColaboradorRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/insertarColaboradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse insertarColaborador(SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/insertarColaboradorRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/insertarColaboradorResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse> insertarColaboradorAsync(SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse listarColaboradores(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse> listarColaboradoresAsync(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresXJefeRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresXJefeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse listarColaboradoresXJefe(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresXJefeRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/listarColaboradoresXJefeResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse> listarColaboradoresXJefeAsync(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/buscarJefeRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/buscarJefeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse buscarJefe(SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sed.pucp.edu.pe/ColaboradorWS/buscarJefeRequest", ReplyAction="http://services.sed.pucp.edu.pe/ColaboradorWS/buscarJefeResponse")]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse> buscarJefeAsync(SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class colaborador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacField;
        
        private bool fechaNacFieldSpecified;
        
        private gerencia gerenciaField;
        
        private int idColaboradorField;
        
        private colaborador jefeField;
        
        private string nombresField;
        
        private periodo periodoField;
        
        private puestoTrabajo puestoTrabajoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
                this.RaisePropertyChanged("fechaNac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacSpecified {
            get {
                return this.fechaNacFieldSpecified;
            }
            set {
                this.fechaNacFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public gerencia gerencia {
            get {
                return this.gerenciaField;
            }
            set {
                this.gerenciaField = value;
                this.RaisePropertyChanged("gerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idColaborador {
            get {
                return this.idColaboradorField;
            }
            set {
                this.idColaboradorField = value;
                this.RaisePropertyChanged("idColaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public colaborador jefe {
            get {
                return this.jefeField;
            }
            set {
                this.jefeField = value;
                this.RaisePropertyChanged("jefe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public puestoTrabajo puestoTrabajo {
            get {
                return this.puestoTrabajoField;
            }
            set {
                this.puestoTrabajoField = value;
                this.RaisePropertyChanged("puestoTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class gerencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idGerenciaField;
        
        private string nombreField;
        
        private periodo periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idGerencia {
            get {
                return this.idGerenciaField;
            }
            set {
                this.idGerenciaField = value;
                this.RaisePropertyChanged("idGerencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class periodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime diaNotificacionField;
        
        private bool diaNotificacionFieldSpecified;
        
        private estadoPeriodo estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private time horaNotificacionField;
        
        private int idPeriodoField;
        
        private string nombreField;
        
        private double pesoEvalCompField;
        
        private double pesoEvalObjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime diaNotificacion {
            get {
                return this.diaNotificacionField;
            }
            set {
                this.diaNotificacionField = value;
                this.RaisePropertyChanged("diaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaNotificacionSpecified {
            get {
                return this.diaNotificacionFieldSpecified;
            }
            set {
                this.diaNotificacionFieldSpecified = value;
                this.RaisePropertyChanged("diaNotificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPeriodo estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public time horaNotificacion {
            get {
                return this.horaNotificacionField;
            }
            set {
                this.horaNotificacionField = value;
                this.RaisePropertyChanged("horaNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPeriodo {
            get {
                return this.idPeriodoField;
            }
            set {
                this.idPeriodoField = value;
                this.RaisePropertyChanged("idPeriodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pesoEvalComp {
            get {
                return this.pesoEvalCompField;
            }
            set {
                this.pesoEvalCompField = value;
                this.RaisePropertyChanged("pesoEvalComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double pesoEvalObj {
            get {
                return this.pesoEvalObjField;
            }
            set {
                this.pesoEvalObjField = value;
                this.RaisePropertyChanged("pesoEvalObj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public enum estadoPeriodo {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        ELIMINADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class time : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sed.pucp.edu.pe/")]
    public partial class puestoTrabajo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idPuestoTrabajoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPuestoTrabajo {
            get {
                return this.idPuestoTrabajoField;
            }
            set {
                this.idPuestoTrabajoField = value;
                this.RaisePropertyChanged("idPuestoTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarColaborador", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarColaboradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ColaboradorWS.colaborador colaborador;
        
        public insertarColaboradorRequest() {
        }
        
        public insertarColaboradorRequest(SistemaEDInterfaces.ColaboradorWS.colaborador colaborador) {
            this.colaborador = colaborador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarColaboradorResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarColaboradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarColaboradorResponse() {
        }
        
        public insertarColaboradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarColaboradores", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarColaboradoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPuestoTrabajo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNI;
        
        public listarColaboradoresRequest() {
        }
        
        public listarColaboradoresRequest(int idPuestoTrabajo, string DNI) {
            this.idPuestoTrabajo = idPuestoTrabajo;
            this.DNI = DNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarColaboradoresResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarColaboradoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ColaboradorWS.colaborador[] @return;
        
        public listarColaboradoresResponse() {
        }
        
        public listarColaboradoresResponse(SistemaEDInterfaces.ColaboradorWS.colaborador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarColaboradoresXJefe", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarColaboradoresXJefeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefe;
        
        public listarColaboradoresXJefeRequest() {
        }
        
        public listarColaboradoresXJefeRequest(int idJefe) {
            this.idJefe = idJefe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarColaboradoresXJefeResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarColaboradoresXJefeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ColaboradorWS.colaborador[] @return;
        
        public listarColaboradoresXJefeResponse() {
        }
        
        public listarColaboradoresXJefeResponse(SistemaEDInterfaces.ColaboradorWS.colaborador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarJefe", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarJefeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefe;
        
        public buscarJefeRequest() {
        }
        
        public buscarJefeRequest(int idJefe) {
            this.idJefe = idJefe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarJefeResponse", WrapperNamespace="http://services.sed.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarJefeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sed.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaEDInterfaces.ColaboradorWS.colaborador @return;
        
        public buscarJefeResponse() {
        }
        
        public buscarJefeResponse(SistemaEDInterfaces.ColaboradorWS.colaborador @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColaboradorWSChannel : SistemaEDInterfaces.ColaboradorWS.ColaboradorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColaboradorWSClient : System.ServiceModel.ClientBase<SistemaEDInterfaces.ColaboradorWS.ColaboradorWS>, SistemaEDInterfaces.ColaboradorWS.ColaboradorWS {
        
        public ColaboradorWSClient() {
        }
        
        public ColaboradorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColaboradorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.insertarColaborador(SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest request) {
            return base.Channel.insertarColaborador(request);
        }
        
        public int insertarColaborador(SistemaEDInterfaces.ColaboradorWS.colaborador colaborador) {
            SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest inValue = new SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest();
            inValue.colaborador = colaborador;
            SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse retVal = ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).insertarColaborador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse> SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.insertarColaboradorAsync(SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest request) {
            return base.Channel.insertarColaboradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.insertarColaboradorResponse> insertarColaboradorAsync(SistemaEDInterfaces.ColaboradorWS.colaborador colaborador) {
            SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest inValue = new SistemaEDInterfaces.ColaboradorWS.insertarColaboradorRequest();
            inValue.colaborador = colaborador;
            return ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).insertarColaboradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.listarColaboradores(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest request) {
            return base.Channel.listarColaboradores(request);
        }
        
        public SistemaEDInterfaces.ColaboradorWS.colaborador[] listarColaboradores(int idPuestoTrabajo, string DNI) {
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest inValue = new SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest();
            inValue.idPuestoTrabajo = idPuestoTrabajo;
            inValue.DNI = DNI;
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse retVal = ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).listarColaboradores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse> SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.listarColaboradoresAsync(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest request) {
            return base.Channel.listarColaboradoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresResponse> listarColaboradoresAsync(int idPuestoTrabajo, string DNI) {
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest inValue = new SistemaEDInterfaces.ColaboradorWS.listarColaboradoresRequest();
            inValue.idPuestoTrabajo = idPuestoTrabajo;
            inValue.DNI = DNI;
            return ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).listarColaboradoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.listarColaboradoresXJefe(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest request) {
            return base.Channel.listarColaboradoresXJefe(request);
        }
        
        public SistemaEDInterfaces.ColaboradorWS.colaborador[] listarColaboradoresXJefe(int idJefe) {
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest inValue = new SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest();
            inValue.idJefe = idJefe;
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse retVal = ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).listarColaboradoresXJefe(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse> SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.listarColaboradoresXJefeAsync(SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest request) {
            return base.Channel.listarColaboradoresXJefeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeResponse> listarColaboradoresXJefeAsync(int idJefe) {
            SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest inValue = new SistemaEDInterfaces.ColaboradorWS.listarColaboradoresXJefeRequest();
            inValue.idJefe = idJefe;
            return ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).listarColaboradoresXJefeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.buscarJefe(SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest request) {
            return base.Channel.buscarJefe(request);
        }
        
        public SistemaEDInterfaces.ColaboradorWS.colaborador buscarJefe(int idJefe) {
            SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest inValue = new SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest();
            inValue.idJefe = idJefe;
            SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse retVal = ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).buscarJefe(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse> SistemaEDInterfaces.ColaboradorWS.ColaboradorWS.buscarJefeAsync(SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest request) {
            return base.Channel.buscarJefeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaEDInterfaces.ColaboradorWS.buscarJefeResponse> buscarJefeAsync(int idJefe) {
            SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest inValue = new SistemaEDInterfaces.ColaboradorWS.buscarJefeRequest();
            inValue.idJefe = idJefe;
            return ((SistemaEDInterfaces.ColaboradorWS.ColaboradorWS)(this)).buscarJefeAsync(inValue);
        }
    }
}
